name: cae
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  adaptive_navigation: ^0.0.7
  colours: ^0.0.2
  flutter_alarm_clock: ^0.0.2
  change_app_package_name: ^1.1.0
  responsive_sizer: ^3.1.1
  shared_preferences: ^2.0.20
  intl: any
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  

dev_dependencies:
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:

  uses-material-design: true
flutter_intl:
  enabled: true
